#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

try:
    from PyQt5.QtCore import *
    from PyQt5.QtWidgets import QApplication
except ImportError:
    print("%s: Please install correctly PyQt5" % (sys.argv[0]))
    sys.exit(1)

from MainWindow import *

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
