#!/bin/bash

if [ ! -d "./venv" ]; then
    virtualenv -p /usr/bin/python3.3 $PWD/venv
    cp -r libs/* venv/lib/python3.3/site-packages/
fi

source ./venv/bin/activate
./venv/bin/python3 BMail.py
deactivate
