#! /usr/bin/env python3

from PyQt5.QtCore import *
from PyQt5.QtWidgets import QApplication

from MainWindow import *

if __name__ == '__main__':

    import sys

    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
