MonCompte:
 mode: imap
 username: bmailisshit@gmail.com
 password: bullshitonbocal
 hostname: imap.gmail.com
 port: 0
 ssl: True
 path: INBOX
MonAutreCompte:
 mode: pop3
 username: bmailisshit@gmail.com
 password: bullshitonbocal
 host: pop.gmail.com
 port: 0
 ssl: True
 path: INBOX